FROM python:3.12-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -e ".[forward]"
ENV PORT=8080
CMD exec gunicorn --bind :${PORT} --workers 1 --threads 8 --timeout 0 src.forward_logging.ingress:app
